name: StartEC2

on: push

jobs:
  build:
    name: Connect To EC2
    runs-on: ubuntu-latest
    steps:
      - name: Download AWS CLi
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Start AWS EC2
        run: |
          aws ec2 start-instance --instance-ids ${{secrets.AWS_EC2_INSTANCE_ID}}
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          AWS_DEFAULT_REGION: "${{ secrets.AWS_REGION }}"

        




