name: prod build and deploy

on: [pull_request,push]

env:
  AWS_REGION: ap-northeast-2
  NODE_VERSION: 14

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup NodeJs environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Test Node
        run: node install